kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile
provisioner: kubernetes.io/azure-file
mountOptions:
  - uid=1000
  - gid=1000
  - dir_mode=0755
  - file_mode=0755
parameters:
  storageAccount: ohaksminecraftlogs
