apiVersion: v1
kind: Service
metadata:
  name: minecraft-svc
  labels:
    app: minecraft
spec:
  ports:
  - port: 25565
    name: minecraftmain
    targetPort: 25565
  - port: 25575
    name: minecraftrcon
    targetPort: 25575
  sessionAffinity: ClientIP
  type: LoadBalancer
  selector:
    app: minecraft
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: StatefulSet
metadata:
  name: minecraft
  labels:
    app: minecraft
spec:
  serviceName: "minecraft-svc"
  selector:
    matchLabels:
      app: minecraft
  replicas: 
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - name: minecraft
        image: openhack/minecraft-server:2.0
        env:
          - name: EULA
            value: "true"
        ports:
        - containerPort: 25565
          name: minecraftmain
        - containerPort: 25575
          name: minecraftrcon
        volumeMounts:
        - name: www
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      storageClassName: azurefile