apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk
  annotations:
    volume.beta.kubernetes.io/storage-class: managed-premium
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  labels:
    run: minecraft
  name: minecraft
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: minecraft
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: minecraft
    spec:
      containers:
      - env:
        - name: EULA
          value: "true"
        image: openhack/minecraft-server:2.0
        imagePullPolicy: IfNotPresent
        name: minecraft
        ports:
        - containerPort: 25565
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: "/data"
          name: volume
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: azure-managed-disk
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: minecraft
  name: minecraft-service
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: 25565
    targetPort: 25565
  selector:
    run: minecraft
  sessionAffinity: None
  type: LoadBalancer